language: node_js

node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - npm install
  - npm install coveralls --save-dev

script:
  - eslint
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
